#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EmployeeDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  partial void InsertLeaveRequest(LeaveRequest instance);
  partial void UpdateLeaveRequest(LeaveRequest instance);
  partial void DeleteLeaveRequest(LeaveRequest instance);
  partial void Insertdepartment(department instance);
  partial void Updatedepartment(department instance);
  partial void Deletedepartment(department instance);
  partial void InsertEmployee(Employee instance);
  partial void UpdateEmployee(Employee instance);
  partial void DeleteEmployee(Employee instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EmployeeDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
	
	public System.Data.Linq.Table<LeaveRequest> LeaveRequests
	{
		get
		{
			return this.GetTable<LeaveRequest>();
		}
	}
	
	public System.Data.Linq.Table<department> departments
	{
		get
		{
			return this.GetTable<department>();
		}
	}
	
	public System.Data.Linq.Table<Employee> Employees
	{
		get
		{
			return this.GetTable<Employee>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserID;
	
	private string _Username;
	
	private string _Password;
	
	private string _Role;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
	
	public User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Role
	{
		get
		{
			return this._Role;
		}
		set
		{
			if ((this._Role != value))
			{
				this.OnRoleChanging(value);
				this.SendPropertyChanging();
				this._Role = value;
				this.SendPropertyChanged("Role");
				this.OnRoleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LeaveRequests")]
public partial class LeaveRequest : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _leave_id;
	
	private System.Nullable<int> _emp_id;
	
	private string _leave_type;
	
	private System.Nullable<System.DateTime> _start_date;
	
	private System.Nullable<System.DateTime> _end_date;
	
	private string _reason;
	
	private string _status;
	
	private string _admin_remarks;
	
	private System.Nullable<System.DateTime> _request_date;
	
	private EntityRef<Employee> _Employee;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onleave_idChanging(int value);
    partial void Onleave_idChanged();
    partial void Onemp_idChanging(System.Nullable<int> value);
    partial void Onemp_idChanged();
    partial void Onleave_typeChanging(string value);
    partial void Onleave_typeChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onadmin_remarksChanging(string value);
    partial void Onadmin_remarksChanged();
    partial void Onrequest_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onrequest_dateChanged();
    #endregion
	
	public LeaveRequest()
	{
		this._Employee = default(EntityRef<Employee>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int leave_id
	{
		get
		{
			return this._leave_id;
		}
		set
		{
			if ((this._leave_id != value))
			{
				this.Onleave_idChanging(value);
				this.SendPropertyChanging();
				this._leave_id = value;
				this.SendPropertyChanged("leave_id");
				this.Onleave_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int")]
	public System.Nullable<int> emp_id
	{
		get
		{
			return this._emp_id;
		}
		set
		{
			if ((this._emp_id != value))
			{
				if (this._Employee.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onemp_idChanging(value);
				this.SendPropertyChanging();
				this._emp_id = value;
				this.SendPropertyChanged("emp_id");
				this.Onemp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_type", DbType="VarChar(50)")]
	public string leave_type
	{
		get
		{
			return this._leave_type;
		}
		set
		{
			if ((this._leave_type != value))
			{
				this.Onleave_typeChanging(value);
				this.SendPropertyChanging();
				this._leave_type = value;
				this.SendPropertyChanged("leave_type");
				this.Onleave_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="Date")]
	public System.Nullable<System.DateTime> start_date
	{
		get
		{
			return this._start_date;
		}
		set
		{
			if ((this._start_date != value))
			{
				this.Onstart_dateChanging(value);
				this.SendPropertyChanging();
				this._start_date = value;
				this.SendPropertyChanged("start_date");
				this.Onstart_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="Date")]
	public System.Nullable<System.DateTime> end_date
	{
		get
		{
			return this._end_date;
		}
		set
		{
			if ((this._end_date != value))
			{
				this.Onend_dateChanging(value);
				this.SendPropertyChanging();
				this._end_date = value;
				this.SendPropertyChanged("end_date");
				this.Onend_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="VarChar(255)")]
	public string reason
	{
		get
		{
			return this._reason;
		}
		set
		{
			if ((this._reason != value))
			{
				this.OnreasonChanging(value);
				this.SendPropertyChanging();
				this._reason = value;
				this.SendPropertyChanged("reason");
				this.OnreasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_remarks", DbType="VarChar(255)")]
	public string admin_remarks
	{
		get
		{
			return this._admin_remarks;
		}
		set
		{
			if ((this._admin_remarks != value))
			{
				this.Onadmin_remarksChanging(value);
				this.SendPropertyChanging();
				this._admin_remarks = value;
				this.SendPropertyChanged("admin_remarks");
				this.Onadmin_remarksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> request_date
	{
		get
		{
			return this._request_date;
		}
		set
		{
			if ((this._request_date != value))
			{
				this.Onrequest_dateChanging(value);
				this.SendPropertyChanging();
				this._request_date = value;
				this.SendPropertyChanged("request_date");
				this.Onrequest_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_LeaveRequest", Storage="_Employee", ThisKey="emp_id", OtherKey="emp_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public Employee Employee
	{
		get
		{
			return this._Employee.Entity;
		}
		set
		{
			Employee previousValue = this._Employee.Entity;
			if (((previousValue != value) 
						|| (this._Employee.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Employee.Entity = null;
					previousValue.LeaveRequests.Remove(this);
				}
				this._Employee.Entity = value;
				if ((value != null))
				{
					value.LeaveRequests.Add(this);
					this._emp_id = value.emp_id;
				}
				else
				{
					this._emp_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("Employee");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.department")]
public partial class department : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dept_id;
	
	private string _dept_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondept_idChanging(int value);
    partial void Ondept_idChanged();
    partial void Ondept_nameChanging(string value);
    partial void Ondept_nameChanged();
    #endregion
	
	public department()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dept_id
	{
		get
		{
			return this._dept_id;
		}
		set
		{
			if ((this._dept_id != value))
			{
				this.Ondept_idChanging(value);
				this.SendPropertyChanging();
				this._dept_id = value;
				this.SendPropertyChanged("dept_id");
				this.Ondept_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_name", DbType="VarChar(200)")]
	public string dept_name
	{
		get
		{
			return this._dept_name;
		}
		set
		{
			if ((this._dept_name != value))
			{
				this.Ondept_nameChanging(value);
				this.SendPropertyChanging();
				this._dept_name = value;
				this.SendPropertyChanged("dept_name");
				this.Ondept_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _emp_id;
	
	private string _name;
	
	private string _email;
	
	private long _phone_number;
	
	private string _designation;
	
	private System.DateTime _date_of_joining;
	
	private decimal _salary;
	
	private string _password;
	
	private System.Data.Linq.Binary _ProfilePicture;
	
	private EntitySet<LeaveRequest> _LeaveRequests;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onphone_numberChanging(long value);
    partial void Onphone_numberChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void Ondate_of_joiningChanging(System.DateTime value);
    partial void Ondate_of_joiningChanged();
    partial void OnsalaryChanging(decimal value);
    partial void OnsalaryChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnProfilePictureChanging(System.Data.Linq.Binary value);
    partial void OnProfilePictureChanged();
    #endregion
	
	public Employee()
	{
		this._LeaveRequests = new EntitySet<LeaveRequest>(new Action<LeaveRequest>(this.attach_LeaveRequests), new Action<LeaveRequest>(this.detach_LeaveRequests));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int emp_id
	{
		get
		{
			return this._emp_id;
		}
		set
		{
			if ((this._emp_id != value))
			{
				this.Onemp_idChanging(value);
				this.SendPropertyChanging();
				this._emp_id = value;
				this.SendPropertyChanged("emp_id");
				this.Onemp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="BigInt NOT NULL")]
	public long phone_number
	{
		get
		{
			return this._phone_number;
		}
		set
		{
			if ((this._phone_number != value))
			{
				this.Onphone_numberChanging(value);
				this.SendPropertyChanging();
				this._phone_number = value;
				this.SendPropertyChanged("phone_number");
				this.Onphone_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string designation
	{
		get
		{
			return this._designation;
		}
		set
		{
			if ((this._designation != value))
			{
				this.OndesignationChanging(value);
				this.SendPropertyChanging();
				this._designation = value;
				this.SendPropertyChanged("designation");
				this.OndesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_joining", DbType="Date NOT NULL")]
	public System.DateTime date_of_joining
	{
		get
		{
			return this._date_of_joining;
		}
		set
		{
			if ((this._date_of_joining != value))
			{
				this.Ondate_of_joiningChanging(value);
				this.SendPropertyChanging();
				this._date_of_joining = value;
				this.SendPropertyChanged("date_of_joining");
				this.Ondate_of_joiningChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Decimal(10,2) NOT NULL")]
	public decimal salary
	{
		get
		{
			return this._salary;
		}
		set
		{
			if ((this._salary != value))
			{
				this.OnsalaryChanging(value);
				this.SendPropertyChanging();
				this._salary = value;
				this.SendPropertyChanged("salary");
				this.OnsalaryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(250)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePicture", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary ProfilePicture
	{
		get
		{
			return this._ProfilePicture;
		}
		set
		{
			if ((this._ProfilePicture != value))
			{
				this.OnProfilePictureChanging(value);
				this.SendPropertyChanging();
				this._ProfilePicture = value;
				this.SendPropertyChanged("ProfilePicture");
				this.OnProfilePictureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_LeaveRequest", Storage="_LeaveRequests", ThisKey="emp_id", OtherKey="emp_id")]
	public EntitySet<LeaveRequest> LeaveRequests
	{
		get
		{
			return this._LeaveRequests;
		}
		set
		{
			this._LeaveRequests.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_LeaveRequests(LeaveRequest entity)
	{
		this.SendPropertyChanging();
		entity.Employee = this;
	}
	
	private void detach_LeaveRequests(LeaveRequest entity)
	{
		this.SendPropertyChanging();
		entity.Employee = null;
	}
}
#pragma warning restore 1591
